### ISSUE TITLE
mega menu only support multi-language from mainmenu, how to support one language one menu function? 

### ISSUE THREAD

**Issue by T3fan** [t3framework/t3#135]
mega menu only read multi-language from one menu, all manul is joomla 1.7 mode,  multi-languages menu must create in mainmenu within this mode, if choose this mode, all language menus under  mainmenu, mainmenu looks so confusion.

i advise Joomlart team change the function and make mega menu  read multi-language from multi-menus, like joomla menu mode, you can create multi-languages menu  in different menus within this mode, joomla2.x  menu and joomla3.x support this function. one language one menu. i like the mode, Convenient Management different language menus. and you can freely switch the mode between mega menu and joomla menu.

**Comment by Ruslannnn** [comment]
hi, I cannot find a megamenu toolbox in joomla 2.5, where is it? I read that I must open megamenu configuration, and save it without any changes, but cannot find megamenu configuration (toolbox). Thanks.

**Comment by Seswu** [comment]
The instruction above, is it still valid?
> T3 does provide a simpler method for multi-languages menu. Just create two menu, but name it in a simple format.
> For ex: the menu for English name 'mymenu' and French should name to 'mymenu-fr'. T3 will detect and auto switch to 'mymenu-fr' if you view the website in French language. You do not have to create two template style and assign them to each menu.

It doesn't seem to work for me, and there's several guides on the 'net advising to duplicate the template style instead.

However.. only needing to duplicate the menu is what would make sense, I think.

It seems pointless and, in the long run, stupid, to duplicate style and layout in order to have a multilanguage setup.
Later on I'd have to replicate changes to one layout in every other layout and, worse, need to remember whether or not one layout is or isn't different from the others.
